# SPDX-License-Identifier: ISC
#
# Makefile for brcmfmac_hwsim - simulated bus module for brcmfmac testing
#

ccflags-y += \
	-I $(src) \
	-I $(src)/.. \
	-I $(src)/../../include

obj-m += brcmfmac_hwsim.o
brcmfmac_hwsim-objs += \
		hwsim_core.o
